//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Aut.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IAutListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class AutBaseListener : IAutListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] AutParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] AutParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.page"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPage([NotNull] AutParser.PageContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.page"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPage([NotNull] AutParser.PageContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="AutParser.block_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNormalBlock([NotNull] AutParser.NormalBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalBlock</c>
	/// labeled alternative in <see cref="AutParser.block_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNormalBlock([NotNull] AutParser.NormalBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NestedBlock</c>
	/// labeled alternative in <see cref="AutParser.block_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNestedBlock([NotNull] AutParser.NestedBlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NestedBlock</c>
	/// labeled alternative in <see cref="AutParser.block_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNestedBlock([NotNull] AutParser.NestedBlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.stringList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringList([NotNull] AutParser.StringListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.stringList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringList([NotNull] AutParser.StringListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlock([NotNull] AutParser.BlockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlock([NotNull] AutParser.BlockContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.connection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnection([NotNull] AutParser.ConnectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.connection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnection([NotNull] AutParser.ConnectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.blankConnection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBlankConnection([NotNull] AutParser.BlankConnectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.blankConnection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBlankConnection([NotNull] AutParser.BlankConnectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.xy_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterXy_pair([NotNull] AutParser.Xy_pairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.xy_pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitXy_pair([NotNull] AutParser.Xy_pairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.connection_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConnection_line([NotNull] AutParser.Connection_lineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.connection_line"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConnection_line([NotNull] AutParser.Connection_lineContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
