//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Aut.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AutParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IAutListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] AutParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] AutParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPage([NotNull] AutParser.PageContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPage([NotNull] AutParser.PageContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.block_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock_list([NotNull] AutParser.Block_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.block_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock_list([NotNull] AutParser.Block_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.stringList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStringList([NotNull] AutParser.StringListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.stringList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStringList([NotNull] AutParser.StringListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] AutParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] AutParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.connection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnection([NotNull] AutParser.ConnectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.connection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnection([NotNull] AutParser.ConnectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.blankConnection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlankConnection([NotNull] AutParser.BlankConnectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.blankConnection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlankConnection([NotNull] AutParser.BlankConnectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.xy_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterXy_pair([NotNull] AutParser.Xy_pairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.xy_pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitXy_pair([NotNull] AutParser.Xy_pairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutParser.connection_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConnection_line([NotNull] AutParser.Connection_lineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutParser.connection_line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConnection_line([NotNull] AutParser.Connection_lineContext context);
}
